In [1]:
import torch
import torch.nn as nn
import pandas as pd
from scipy.io.arff import loadarff
import numpy as np

In [2]:
def baseline(dim):
    baseline_model = nn.Sequential(
        nn.Linear(dim, 256, dtype=torch.float64),
        nn.ReLU(),
        nn.Linear(256, 64, dtype=torch.float64),
        nn.ReLU(),
        nn.Linear(64, 64, dtype=torch.float64),
        nn.ReLU(),
        nn.Linear(64, 256, dtype=torch.float64),
        nn.ReLU(),
        nn.Linear(256, 1, dtype=torch.float64),
        nn.Sigmoid()
    )

    return baseline_model

## Обработка данных 2

In [272]:
raw_data = loadarff("data/electricity-normalized.arff")
df_data = pd.DataFrame(raw_data[0])

In [273]:
df_data['day'] = df_data['day'].astype('int32')

In [274]:
df_data

date  day    period  nswprice  nswdemand  vicprice  vicdemand  \
0      0.0000    2  0.000000  0.056443   0.439155  0.003467   0.422915   
1      0.0000    2  0.021277  0.051699   0.415055  0.003467   0.422915   
2      0.0000    2  0.042553  0.051489   0.385004  0.003467   0.422915   
3      0.0000    2  0.063830  0.045485   0.314639  0.003467   0.422915   
4      0.0000    2  0.085106  0.042482   0.251116  0.003467   0.422915   
...       ...  ...       ...       ...        ...       ...        ...   
45307  0.9158    7  0.914894  0.044224   0.340672  0.003033   0.255049   
45308  0.9158    7  0.936170  0.044884   0.355549  0.003072   0.241326   
45309  0.9158    7  0.957447  0.043593   0.340970  0.002983   0.247799   
45310  0.9158    7  0.978723  0.066651   0.329366  0.004630   0.345417   
45311  0.9158    7  1.000000  0.050679   0.288753  0.003542   0.355256   

       transfer    class  
0      0.414912    b'UP'  
1      0.414912    b'UP'  
2      0.414912    b'UP'  
3      0.414912    b'UP'  
4      0.414912  b'DOWN'  
...         ...      ...  
45307  0.405263  b'DOWN'  
45308  0.420614  b'DOWN'  
45309  0.362281  b'DOWN'  
45310  0.206579    b'UP'  
45311  0.231140  b'DOWN'  

[45312 rows x 9 columns]

In [275]:
target = df_data['class'].to_numpy()
target[target==b'UP'] = 1
target[target==b'DOWN'] = 0
target = target.astype(dtype=int)

In [276]:
target

array([1, 1, 1, ..., 0, 1, 0])

In [277]:
feature = df_data[['date', 'day', 'period', 'nswprice', 'nswdemand', 'vicprice', 'vicdemand', 'transfer']]

## Данные для первого датасета

In [224]:
raw_data = loadarff("data/phpkIxskf.arff")
df_data = pd.DataFrame(raw_data[0])

In [225]:
target = df_data.iloc[:, -1].values

In [241]:
target[target==b'1'] = 0
target[target==b'2'] = 1
target = target.astype(int)

In [242]:
np.unique(target)

array([0, 1])

In [243]:
features = df_data.iloc[:, :-1]

In [244]:
features

V1               V2           V3            V4     V5      V6  \
0      58.0    b'management'   b'married'   b'tertiary'  b'no'  2143.0   
1      44.0    b'technician'    b'single'  b'secondary'  b'no'    29.0   
2      33.0  b'entrepreneur'   b'married'  b'secondary'  b'no'     2.0   
3      47.0   b'blue-collar'   b'married'    b'unknown'  b'no'  1506.0   
4      33.0       b'unknown'    b'single'    b'unknown'  b'no'     1.0   
...     ...              ...          ...           ...    ...     ...   
45206  51.0    b'technician'   b'married'   b'tertiary'  b'no'   825.0   
45207  71.0       b'retired'  b'divorced'    b'primary'  b'no'  1729.0   
45208  72.0       b'retired'   b'married'  b'secondary'  b'no'  5715.0   
45209  57.0   b'blue-collar'   b'married'  b'secondary'  b'no'   668.0   
45210  37.0  b'entrepreneur'   b'married'  b'secondary'  b'no'  2971.0   

           V7      V8            V9   V10     V11     V12  V13    V14   V15  \
0      b'yes'   b'no'    b'unknown'   5.0  b'may'   261.0  1.0   -1.0   0.0   
1      b'yes'   b'no'    b'unknown'   5.0  b'may'   151.0  1.0   -1.0   0.0   
2      b'yes'  b'yes'    b'unknown'   5.0  b'may'    76.0  1.0   -1.0   0.0   
3      b'yes'   b'no'    b'unknown'   5.0  b'may'    92.0  1.0   -1.0   0.0   
4       b'no'   b'no'    b'unknown'   5.0  b'may'   198.0  1.0   -1.0   0.0   
...       ...     ...           ...   ...     ...     ...  ...    ...   ...   
45206   b'no'   b'no'   b'cellular'  17.0  b'nov'   977.0  3.0   -1.0   0.0   
45207   b'no'   b'no'   b'cellular'  17.0  b'nov'   456.0  2.0   -1.0   0.0   
45208   b'no'   b'no'   b'cellular'  17.0  b'nov'  1127.0  5.0  184.0   3.0   
45209   b'no'   b'no'  b'telephone'  17.0  b'nov'   508.0  4.0   -1.0   0.0   
45210   b'no'   b'no'   b'cellular'  17.0  b'nov'   361.0  2.0  188.0  11.0   

              V16  
0      b'unknown'  
1      b'unknown'  
2      b'unknown'  
3      b'unknown'  
4      b'unknown'  
...           ...  
45206  b'unknown'  
45207  b'unknown'  
45208  b'success'  
45209  b'unknown'  
45210    b'other'  

[45211 rows x 16 columns]

In [245]:
feature = features[['V1', 'V6', 'V10', 'V12', 'V13', 'V14', 'V15']]

In [58]:
b_model = baseline(7)

In [42]:
batch_size = 2000
num_epochs = 2000
min_loss, t = np.inf, 0

In [43]:
optimizer = torch.optim.Adam(b_model.parameters(), lr=1e-4, eps=1e-4)

In [13]:
b_model.train()

Sequential(
  (0): Linear(in_features=7, out_features=256, bias=True)
  (1): ReLU()
  (2): Linear(in_features=256, out_features=64, bias=True)
  (3): ReLU()
  (4): Linear(in_features=64, out_features=64, bias=True)
  (5): ReLU()
  (6): Linear(in_features=64, out_features=256, bias=True)
  (7): ReLU()
  (8): Linear(in_features=256, out_features=1, bias=True)
  (9): Sigmoid()
)

In [42]:
[features[key].values for key in features.keys()]

[array([58., 44., 33., ..., 72., 57., 37.]),
 array([b'management', b'technician', b'entrepreneur', ..., b'retired',
        b'blue-collar', b'entrepreneur'], dtype=object),
 array([b'married', b'single', b'married', ..., b'married', b'married',
        b'married'], dtype=object),
 array([b'tertiary', b'secondary', b'secondary', ..., b'secondary',
        b'secondary', b'secondary'], dtype=object),
 array([b'no', b'no', b'no', ..., b'no', b'no', b'no'], dtype=object),
 array([2.143e+03, 2.900e+01, 2.000e+00, ..., 5.715e+03, 6.680e+02,
        2.971e+03]),
 array([b'yes', b'yes', b'yes', ..., b'no', b'no', b'no'], dtype=object),
 array([b'no', b'no', b'yes', ..., b'no', b'no', b'no'], dtype=object),
 array([b'unknown', b'unknown', b'unknown', ..., b'cellular', b'telephone',
        b'cellular'], dtype=object),
 array([ 5.,  5.,  5., ..., 17., 17., 17.]),
 array([b'may', b'may', b'may', ..., b'nov', b'nov', b'nov'], dtype=object),
 array([ 261.,  151.,   76., ..., 1127.,  508.,  361.]),


In [12]:
for col, dtype in features.dtypes.items():
    if dtype == np.object:  # Only process byte object columns.
        features[col] = features[col].apply(lambda x: x.decode("utf-8"))

C:\Users\User\AppData\Local\Temp\ipykernel_4428\982722030.py:2: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if dtype == np.object:  # Only process byte object columns.


In [13]:
features = features[['V1', 'V6', 'V10', 'V12', 'V13', 'V14', 'V15']]

In [44]:
grid_tensors = [torch.tensor(feat[key].values) for key in feat.keys()]
grid_tensor = torch.stack(grid_tensors)
grid_flattened = grid_tensor.view(grid_tensor.shape[0], -1).transpose(0, 1)
grid_flattened = grid_flattened.to(grid_flattened.to(torch.float64))

In [45]:
grid_flattened[0]

tensor([ 5.8000e+01,  2.1430e+03,  5.0000e+00,  2.6100e+02,  1.0000e+00,
        -1.0000e+00,  0.0000e+00], dtype=torch.float64)

In [46]:
len(target)
train_features = grid_flattened[:36168]
train_target = target[:36168]
test_features = grid_flattened[36168:]
test_target = target[36168:]

In [17]:
train_features = train_features.to(torch.float64)

## Третьи данные

In [306]:
raw_data = loadarff("data/phpSSK7iA.arff")
df_data = pd.DataFrame(raw_data[0])

In [307]:
df_data

D1        D2    D3   D4        D5        D6        D7        D8  \
0     0.000000  0.497009  0.10  0.0  0.132956  0.678031  0.273166  0.585445   
1     0.366667  0.606291  0.05  0.0  0.111209  0.803455  0.106105  0.411754   
2     0.033300  0.480124  0.00  0.0  0.209791  0.610350  0.356453  0.517720   
3     0.000000  0.538825  0.00  0.5  0.196344  0.724230  0.235606  0.288764   
4     0.100000  0.517794  0.00  0.0  0.494734  0.781422  0.154361  0.303809   
...        ...       ...   ...  ...       ...       ...       ...       ...   
3746  0.033300  0.506409  0.10  0.0  0.209887  0.633426  0.297659  0.376124   
3747  0.133333  0.651023  0.15  0.0  0.151154  0.766505  0.170876  0.404546   
3748  0.200000  0.520564  0.00  0.0  0.179949  0.768785  0.177341  0.471179   
3749  0.100000  0.765646  0.00  0.0  0.536954  0.634936  0.342713  0.447162   
3750  0.133333  0.533952  0.00  0.0  0.347966  0.757971  0.230667  0.272652   

            D9       D10  ...  D1768  D1769  D1770  D1771  D1772  D1773  \
0     0.743663  0.243144  ...    0.0    0.0    0.0    0.0    0.0    0.0   
1     0.836582  0.106480  ...    1.0    1.0    1.0    0.0    1.0    0.0   
2     0.679051  0.352308  ...    0.0    0.0    0.0    0.0    0.0    0.0   
3     0.805110  0.208989  ...    0.0    0.0    0.0    0.0    0.0    0.0   
4     0.812646  0.125177  ...    0.0    0.0    0.0    0.0    0.0    0.0   
...        ...       ...  ...    ...    ...    ...    ...    ...    ...   
3746  0.727093  0.308163  ...    0.0    0.0    0.0    0.0    0.0    0.0   
3747  0.787935  0.192527  ...    0.0    1.0    0.0    1.0    0.0    1.0   
3748  0.872241  0.122132  ...    0.0    0.0    0.0    0.0    0.0    0.0   
3749  0.672689  0.372936  ...    0.0    0.0    0.0    0.0    0.0    0.0   
3750  0.854116  0.140316  ...    0.0    0.0    0.0    0.0    0.0    0.0   

      D1774  D1775  D1776  target  
0       0.0    0.0    0.0    b'1'  
1       0.0    1.0    0.0    b'1'  
2       0.0    0.0    0.0    b'1'  
3       0.0    0.0    0.0    b'1'  
4       0.0    0.0    0.0    b'0'  
...     ...    ...    ...     ...  
3746    0.0    0.0    0.0    b'1'  
3747    0.0    0.0    0.0    b'1'  
3748    0.0    0.0    0.0    b'0'  
3749    0.0    0.0    0.0    b'1'  
3750    0.0    0.0    0.0    b'0'  

[3751 rows x 1777 columns]

In [308]:
target = df_data['target']
target[target==b'1'] = 1
target[target==b'0'] = 0

C:\Users\User\AppData\Local\Temp\ipykernel_9228\1814935476.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  target[target==b'1'] = 1
C:\Users\User\AppData\Local\Temp\ipykernel_9228\1814935476.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  target[target==b'0'] = 0


In [309]:
target = target.astype(int)

In [311]:
ks = list(df_data.keys())
ks = ks[:-1]

In [313]:
feature = df_data[ks]

In [314]:
feature

D1        D2    D3   D4        D5        D6        D7        D8  \
0     0.000000  0.497009  0.10  0.0  0.132956  0.678031  0.273166  0.585445   
1     0.366667  0.606291  0.05  0.0  0.111209  0.803455  0.106105  0.411754   
2     0.033300  0.480124  0.00  0.0  0.209791  0.610350  0.356453  0.517720   
3     0.000000  0.538825  0.00  0.5  0.196344  0.724230  0.235606  0.288764   
4     0.100000  0.517794  0.00  0.0  0.494734  0.781422  0.154361  0.303809   
...        ...       ...   ...  ...       ...       ...       ...       ...   
3746  0.033300  0.506409  0.10  0.0  0.209887  0.633426  0.297659  0.376124   
3747  0.133333  0.651023  0.15  0.0  0.151154  0.766505  0.170876  0.404546   
3748  0.200000  0.520564  0.00  0.0  0.179949  0.768785  0.177341  0.471179   
3749  0.100000  0.765646  0.00  0.0  0.536954  0.634936  0.342713  0.447162   
3750  0.133333  0.533952  0.00  0.0  0.347966  0.757971  0.230667  0.272652   

            D9       D10  ...  D1767  D1768  D1769  D1770  D1771  D1772  \
0     0.743663  0.243144  ...    0.0    0.0    0.0    0.0    0.0    0.0   
1     0.836582  0.106480  ...    1.0    1.0    1.0    1.0    0.0    1.0   
2     0.679051  0.352308  ...    0.0    0.0    0.0    0.0    0.0    0.0   
3     0.805110  0.208989  ...    0.0    0.0    0.0    0.0    0.0    0.0   
4     0.812646  0.125177  ...    0.0    0.0    0.0    0.0    0.0    0.0   
...        ...       ...  ...    ...    ...    ...    ...    ...    ...   
3746  0.727093  0.308163  ...    0.0    0.0    0.0    0.0    0.0    0.0   
3747  0.787935  0.192527  ...    0.0    0.0    1.0    0.0    1.0    0.0   
3748  0.872241  0.122132  ...    0.0    0.0    0.0    0.0    0.0    0.0   
3749  0.672689  0.372936  ...    0.0    0.0    0.0    0.0    0.0    0.0   
3750  0.854116  0.140316  ...    0.0    0.0    0.0    0.0    0.0    0.0   

      D1773  D1774  D1775  D1776  
0       0.0    0.0    0.0    0.0  
1       0.0    0.0    1.0    0.0  
2       0.0    0.0    0.0    0.0  
3       0.0    0.0    0.0    0.0  
4       0.0    0.0    0.0    0.0  
...     ...    ...    ...    ...  
3746    0.0    0.0    0.0    0.0  
3747    1.0    0.0    0.0    0.0  
3748    0.0    0.0    0.0    0.0  
3749    0.0    0.0    0.0    0.0  
3750    0.0    0.0    0.0    0.0  

[3751 rows x 1776 columns]

## simple dataset

In [84]:
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer(return_X_y=True, as_frame=True)

In [87]:
data[1]

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: target, Length: 569, dtype: int32

In [88]:
feature = data[0]
target = data[1]

In [82]:
list(data.target_names)

['malignant', 'benign']

## Модель и её обучение

In [315]:
dims = len(feature.keys())
b_model = baseline(dims)
criterion = nn.BCELoss()
# criterion = nn.MultiLabelSoftMarginLoss()
optimizer = torch.optim.Adam(b_model.parameters(), lr=1e-4, eps=1e-4)
dims

1776

In [316]:
grid_tensors = [torch.tensor(feature[key].values) for key in feature.keys()]
grid_tensor = torch.stack(grid_tensors)
grid_flattened = grid_tensor.view(grid_tensor.shape[0], -1).transpose(0, 1)
grid_flattened = grid_flattened.to(grid_flattened.to(torch.float64))
grid_flattened[0]

tensor([0.0000, 0.4970, 0.1000,  ..., 0.0000, 0.0000, 0.0000],
       dtype=torch.float64)

In [317]:
train_features = grid_flattened
train_target = target

In [318]:
param = len(target) // 100 * 80
train_features = grid_flattened[:param]
train_target = target[:param]
test_features = grid_flattened[param:]
test_target = target[param:]
param

2960

In [319]:
# device = torch.device('cuda')
b_model.train()

Sequential(
  (0): Linear(in_features=1776, out_features=256, bias=True)
  (1): ReLU()
  (2): Linear(in_features=256, out_features=64, bias=True)
  (3): ReLU()
  (4): Linear(in_features=64, out_features=64, bias=True)
  (5): ReLU()
  (6): Linear(in_features=64, out_features=256, bias=True)
  (7): ReLU()
  (8): Linear(in_features=256, out_features=1, bias=True)
  (9): Sigmoid()
)

In [239]:
train_target

array([0, 0, 0, ..., 0, 0, 0], dtype=object)

In [320]:
train_target = torch.tensor(train_target)

In [108]:
train_target[indices]

tensor([1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1],
       dtype=torch.int32)

In [74]:
from sklearn.metrics import roc_curve

In [321]:
batch_size = 2000
# num_epochs = 2000
num_epochs = 1000
min_loss, t = np.inf, 0
for epoch in range(num_epochs):
    permutation = torch.randperm(train_features.size()[0])
    loss_list = []
    for i in range(0, len(train_target), batch_size):
        indices = permutation[i:i+batch_size]
        # print(indices)
        batch_x, target_y = train_features[indices], train_target[indices]
        target_y = target_y.to(torch.float64)
        optimizer.zero_grad()
        output = b_model(batch_x)
        # fpr, tpr, thresholds = roc_curve(target_y, output.detach().numpy())
        # tresh = np.mean(thresholds)
        # output = torch.round(output)
        # output[output < tresh] = 0
        # output[output != 0] = 1
        # target_y = np.array(target_y, dtype=int)


        # loss = -1 * torch.mean(torch.tensor(target_y) * torch.log(output) + torch.tensor((1 - target_y)) * torch.log(1 - output))
        # loss = torch.mean(torch.abs(torch.tensor(target_y) - output))
        loss = criterion(output, target_y.reshape_as(output))
        
        # print(loss)
        loss.backward()
        optimizer.step()
        # print(loss.item())
        loss_list.append(loss.item())
    # print(loss_list)
    loss_mean = np.mean(loss_list)

    t += 1
    print('Surface training t={}, loss={}'.format(t, loss_mean))

Surface training t=1, loss=0.6940646506482357
Surface training t=2, loss=0.6936977014113002
Surface training t=3, loss=0.693337597936442
Surface training t=4, loss=0.6930134513134301
Surface training t=5, loss=0.6926827841417923
Surface training t=6, loss=0.6924673103500043
Surface training t=7, loss=0.6920361970561779
Surface training t=8, loss=0.6916319341136166
Surface training t=9, loss=0.6913881341422448
Surface training t=10, loss=0.6910532290373002
Surface training t=11, loss=0.6909146049292536
Surface training t=12, loss=0.6905733458329515
Surface training t=13, loss=0.6900756929892894
Surface training t=14, loss=0.6898373407139831
Surface training t=15, loss=0.6899781314065478
Surface training t=16, loss=0.6896700563161657
Surface training t=17, loss=0.6894660255045102
Surface training t=18, loss=0.6878942639999683
Surface training t=19, loss=0.6883182393827744
Surface training t=20, loss=0.6882718492945337
Surface training t=21, loss=0.6873332926218523
Surface training t=22, 

In [322]:
ttr = b_model(test_features)

In [323]:
ttr

tensor([[1.0000e+00],
        [8.0870e-04],
        [4.4106e-07],
        [1.0000e+00],
        [8.4816e-01],
        [1.0000e+00],
        [1.0000e+00],
        [1.0000e+00],
        [1.0000e+00],
        [9.9983e-01],
        [9.9919e-01],
        [1.0000e+00],
        [9.9978e-01],
        [5.1414e-06],
        [9.9998e-01],
        [2.0010e-07],
        [1.0000e+00],
        [1.4939e-07],
        [1.0000e+00],
        [4.7520e-08],
        [1.1601e-01],
        [9.9999e-01],
        [1.0836e-02],
        [7.0599e-05],
        [9.9004e-05],
        [1.0000e+00],
        [6.7268e-06],
        [9.5173e-05],
        [4.2931e-03],
        [1.0781e-07],
        [9.9999e-01],
        [3.2123e-01],
        [1.9762e-02],
        [1.0000e+00],
        [1.1335e-04],
        [4.7102e-04],
        [1.0000e+00],
        [2.3816e-03],
        [1.0000e+00],
        [7.7497e-02],
        [3.8397e-03],
        [1.5473e-03],
        [1.0000e+00],
        [7.7944e-10],
        [1.0000e+00],
        [9

In [328]:
target_y = torch.tensor(test_target.to_numpy()).to(torch.float64)
criterion(ttr, target_y.reshape_as(ttr))

tensor(2.9587, dtype=torch.float64, grad_fn=<BinaryCrossEntropyBackward0>)

In [1]:
from ogb.graphproppred import PygGraphPropPredDataset
from torch_geometric.data import DataLoader

# Download and process data at './dataset/ogbg_molhiv/'
dataset = PygGraphPropPredDataset(name = "ogbg-molhiv", root = 'dataset/')

 
split_idx = dataset.get_idx_split() 
train_loader = DataLoader(dataset[split_idx["train"]], batch_size=32, shuffle=True)
valid_loader = DataLoader(dataset[split_idx["valid"]], batch_size=32, shuffle=False)
test_loader = DataLoader(dataset[split_idx["test"]], batch_size=32, shuffle=False)

Downloaded 0.00 GB: 100%|██████████| 3/3 [00:02<00:00,  1.20it/s]
Processing...


Extracting dataset/hiv.zip
Loading necessary files...
This might take a while.
Processing graphs...


100%|██████████| 41127/41127 [00:00<00:00, 112284.98it/s]


Converting graphs into PyG objects...


100%|██████████| 41127/41127 [00:01<00:00, 35330.22it/s]


Saving...


Done!
c:\Python39\lib\site-packages\torch_geometric\deprecation.py:22: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)


In [4]:
train_loader.batch_sampler

In [9]:
split_idx['train']

tensor([    3,     4,     5,  ..., 41124, 41125, 41126])

In [10]:
import matplotlib.pyplot as plt

from sklearn import datasets, manifold

In [ ]:
sr_points, sr_color = datasets.make_swiss_roll(n_samples=1500, random_state=0)